200ok-ch/organice

package.json, src/components/OrgFile/OrgFile.test.js, src/components/OrgFile/__snapshots__/OrgFile.test.js.snap
1. Adds ```@testing-library/react``` as a new Dev dependency.
2. Removes the ```.skip``` from OrgFile-tests and rewrites those tests using the newly added library and its guiding principles:
1. If it relates to rendering components, then it should deal with DOM nodes rather than component instances, and it should not encourage dealing with component instances.
2. It should be generally useful for testing the application components in the way the user would use it. We are making some trade-offs here because we're using a computer and often a simulated browser environment, but in general, utilities should encourage tests that use the components the way they're intended to be used.
3. Utility implementations and APIs should be simple and flexible.
(copied from: …
=> Feature/43/add react testing library and refactor .skipped tests

src/components/UI/Drawer/index.js
Tested on iOS 12 and 13 that the presumed iOS bug does not appear after removing the code.
=> fix: Remove unneeded code that was tagged with "ridiculous hack"

src/components/OrgFile/components/TimestampEditorModal/components/TimestampEditor/index.js
The datepicker was throwing an error when trying to parse the date on clear. If no date is picker, do nothing.
=> fix: error on clearing date picker

src/components/OrgFile/__snapshots__/OrgFile.integration.test.js.snap, src/components/OrgFile/components/Header/index.js
As a user, when I swipe a header, I want the icon to contrast the background, so that better see the action taken
=> Changed the icon color on swipe to contrast the background

src/components/HeaderBar/stylesheet.css, src/components/SyncServiceSignIn/stylesheet.css
Hey folks, thank you for this great project. 
I am not sure if it is a bug, since idk if we are supporting desktop users, but I missed that when first using organice. (a few seconds until I realized that I could click the dropbox logo/item in sign-in page). 
Do you think it is useful? should I create an issue for it?
=> fix: Show clickable links with cursor pointer

README.org, src/actions/org.js, src/components/OrgFile/OrgFile.unit.test.js, src/lib/export_org.js, src/lib/parse_org.js, src/reducers/org.js
They will not be visible and editable for now, but are not lost on
import and export (better than the current situation in my opinion).
This can be viewed as a temporary (perhaps not so beautiful) fix for avoiding information loss until the proper parser is completed.
----
#
=> Keep all in-file settings and content lines from top of file

src/components/OrgFile/components/Header/index.js, src/components/OrgFile/components/HeaderContent/components/LogBookEntries/index.js, src/components/OrgFile/components/HeaderContent/index.js, src/lib/export_org.js, src/lib/parse_org.js, test_helpers/fixtures/logbook.org
Address #111 and (hopefully) #108 (edit: and #110)
Currently, this lacks the ability to edit comments/non-clock lines in the logbook, but will preserve them.
=> Handle non-clock entries in logbook

README.org, src/components/OrgFile/OrgFile.unit.test.js, src/lib/org_utils.js, src/reducers/org.js, test_helpers/fixtures/schedule_with_repeater.org, test_helpers/fixtures/schedule_with_repeater_and_nologrepeat.org, test_helpers/fixtures/schedule_with_repeater_and_nologrepeat_and_other_options.org, test_helpers/fixtures/schedule_with_repeater_and_nologrepeat_property.org
=> If startup option "nologrepeat" is set, don't log repeat information

.circleci/config.yml, Dockerfile, README.org, docker-compose-dev.yaml, docker-compose.yaml
This PR adds support for creating a Docker image from the source code which has  been requested in  #132. 
The Docker image makes it easier to run this service without the need to install the correct versions for `nodejs`, `yarn`, etc.
It also allows users to be able to run this service in a Kubernetes cluster or a Docker Swarm cluster.
This PR is still in progress while a pipeline has to be built around creating the Docker image and pushing it to some registry (e.g. Docker Hub).
=> [WIP] Docker Support

src/components/OrgFile/components/Header/index.js
This PR covers my idea in #100. I think it's an improvement if we put the `HeaderActionDrawer` before the headline instead of placing it after the headline.
=> Feature: Move HeaderActionDrawer before headline

src/components/SyncServiceSignIn/index.js
This PR is just a minimal change, but it provides a better UX for mobile users. It changes the type of the URL input box from `type="text"` to `type="url"`, which enables mobile OSes to use the correct keyboard layout. See [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url).
=> Improve webdav url input

sample.org, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/__snapshots__/OrgFile.integration.test.js.snap, src/components/OrgFile/components/TitleLine/index.js, src/components/OrgFile/components/TitleLine/stylesheet.css, src/lib/org_utils.js
This closes #16 
@munen In case you know at the first glance where to get `todoKeywordSet` from, I'd be happy about a hint. Otherwise I'll figure it out, shouldn't be too hard.
=> Proper coloring of items with DONE state

src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/__snapshots__/OrgFile.integration.test.js.snap, src/components/OrgFile/components/Header/components/HeaderActionDrawer/index.js, src/components/OrgFile/components/TitleLine/index.js, src/reducers/org.js
This should close #20 
@munen When editing the title of a header (pressing the title edit icon), shouldn't we place the curser at the end of the line by default? At least for new headers (with a TODO keyword) this would make very much sense. And for existing headers with much text it wouldn't hurt, what do you think?
=> Place TODO keyword of previous header in the new header

.circleci/config.yml, .dockerignore, Dockerfile
This PR fixes issue #183. It installs `bash` in the docker container, so that the newly introduced bash scripts work without an error. It reverts also 012f00f, but keeps the `.dockerignore` file.
=> Bugfix: Docker build with bash scripts

src/lib/headline_filter.js, src/lib/headline_filter.unit.test.js, src/lib/headline_filter_parser.grammar.pegjs, src/lib/headline_filter_parser.unit.test.js
[This commit](https://github.com/200ok-ch/organice/pull/176/commits/3fd26615cd64add6a1b985a6b662e45130f18cb2) breaks `yarn start` but not `yarn test`
Update: [Fixed](https://github.com/200ok-ch/organice/pull/176/commits/f68d469e6280d4bd06e8a851ff31a33caae96727)
```
Failed to compile.
./src/reducers/org.js
Attempted import error: '../lib/headline_filter_parser' does not contain a default export (imported as 'headline_filter_parser').
```
The generated file `headline_filter_parser.js` – with or without the last commit – exports:
```
module.exports = {
SyntaxError: peg$SyntaxError,
parse:       peg$parse
};
```
It is imported like this:
```
import headline_filter_parser from '../lib/headline_filter_parser';
```
What is the problem? Does it work on the CI here?
=> Support single- and double-quoted strings in the search filter

src/lib/parse_org.js, src/reducers/org.js, test_helpers/fixtures/all_the_features.org
... when capturing via template and when adding/editing a headline.
Makes sense?
I think it does not make sense to have trailing whitespace in any source code. OK, markdown uses trailing whitespace to declare a `<br>` but a headline in emacs does not need trailing space, right?
=> Trim headline title at both sides before saving

changelog.org, package.json, src/components/OrgFile/components/CaptureModal/index.js, src/lib/browser_utils.js, yarn.lock
Some versions of Mobile Safari do _not_ like it when the
focus is set without an explicit user interaction. This is the case
in organice, because the user interaction is on a button which in
turn opens a textarea which should have the focus. It will open the
software keyboard, but the capture template will stay on the bottom
of the view, so it will be hidden by the keyboard. The user would
have to manually scroll down. On iOS 12, it worked without this
workaround. Starting with iOS 13.3, the workaround isn't needed,
anymore.
=> fix: Capture template styling for iOS 13.3+

changelog.org, src/components/OrgFile/components/Header/index.js
As per https://github.com/200ok-ch/organice/issues/188, the changes introduced in https://github.com/200ok-ch/organice/issues/100 didn't fare well with the community. Hence, as a first step to improve UX, we're reverting to the previous state.
=> Revert "Move HeaderActionDrawer before headline"

README.org
`docker run -p 5000:5000 -t organice twohundredok/organice:latest` means running the image named organice which does not exist.
Thanks for organice!
=> Fix docker run line in README

src/components/OrgFile/components/TitleLine/index.js
This PR supersedes #168. As discussed there and in the linked comment, placing the cursor at the end of the input is problematic. But not for newly added headers, that only contain the TODO keyword.
PR #168 can be closed without merge.
=> Place cursor after the TODO keyword when creating a new header

README.org, package.json
Slightly relax the requirements on a particular node engine version, and also document some helpful tips on how to install the correct version.
=> Make node setup easier for dev environments

sample.org, src/components/CaptureTemplatesEditor/index.js, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/components/ActionDrawer/index.js, src/components/OrgFile/components/AttributedString/stylesheet.css, src/lib/headline_filter.unit.test.js, src/lib/org_utils.js, src/lib/parse_org.js, src/reducers/base.js, src/reducers/capture.js, src/reducers/org.js, src/reducers/sync_backend.js, src/util/settings_persister.js
This should close #182: Refactor and clean-up after the search filter PR.
...
=> Refactoring

CONTRIBUTING.org, src/actions/org.js, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/__snapshots__/OrgFile.integration.test.js.snap, src/components/OrgFile/components/ActionDrawer/index.js, src/components/OrgFile/components/AgendaModal/index.js, src/components/OrgFile/components/SearchModal/components/HeaderListView/index.js, src/components/OrgFile/components/SearchModal/components/HeaderListView/stylesheet.css, src/components/OrgFile/components/SearchModal/index.js, src/components/OrgFile/components/SearchModal/stylesheet.css, src/components/OrgFile/components/TaskListModal/components/TaskListView/index.js, src/components/OrgFile/components/TaskListModal/index.js, src/components/OrgFile/index.js, src/reducers/base.js, src/reducers/org.js
A TaskList should just be what the name says - a task list. It totally makes sense to have task specific feature that filters down to tasks and orders them by various task related critieria. Complecting this feature with a more generic "Search" will complicate the interface, the code and the understanding of the user.
Instead of going down that route, I propose to have a TaskList which does just that. Next to it, there is a standalone Search which has fewer features and only filters down on headers.
For the GUI, I've harmonized them into one collapsible FAB, because even though they are doing very different jobs - they are pretty aligned in terms of how they operate.
Open tasks:
@schoettl What do you think - does this work for you?
=> Introduce Search next to TaskList

changelog.org, src/components/HeaderBar/index.js, src/components/HeaderBar/stylesheet.css
This example file is called `things.org`. For brevity, organice shows its name in the header as `things`.
The whole header is constructed with a CSS grid, so it behaves pretty well in constrained conditions. The filename, of course, is the least important, so it will shrink where needed.
=> Show Org filename in Header where applicable

src/components/OrgFile/components/CaptureModal/index.js, src/lib/org_utils.js
I also replaced `!!targetHeader` with `targetHeader` because as far as I know, this `!!` doesn't make sense in many cases. An object never evaluates to false and null always eveluates to false. That is all we are testing here.
Or is there any good reason to keep it?
=> Bugfix: don't crash on using capture template when header path is invalid

src/components/OrgFile/components/Header/components/HeaderActionDrawer/index.js
The mouseover text for these actions had been reversed, this fixes them.
=> Minor: correct widen/narrow text

src/actions/base.js, src/actions/org.js, src/components/OrgFile/OrgFile.unit.test.js, src/components/OrgFile/components/HeaderContent/index.js, src/components/Settings/index.js, src/lib/export_org.js, src/lib/parse_org.unit.test.js, src/reducers/base.js, src/util/settings_persister.js
This is on top of the yet-to-be-merged PR #271.
Here we add support for an `org-adapt-indentation` compatible setting.
By default (`org-adapt-indentation t`), heading body is indented according to the nesting level of the heading. When this new setting is enabled in the organice UI, we follow `org-adapt-indentation nil` instead, i.e. all text is kept flush left.
Some users prefer this, because then they have the option to switch dynamically between indent / no-indent modes with [`org-indent-mode`](https://orgmode.org/manual/Org-Indent-Mode.html).
=> Support org-adapt-indentation

package.json, yarn.lock
Closes https://github.com/200ok-ch/organice/issues/269
According to the [changelog](https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md#200---2019-08-20), we should be good with the upgrade.
I made quick tests in the UI and didn't see regressions, as well.
=> chore: Upgrade date-fns

src/components/Landing/__snapshots__/Landing.test.js.snap, src/components/Landing/index.js, src/components/Landing/stylesheet.css, src/components/PrivacyPolicy/index.js
In particular, the homepage needs more of an explanation of the app, the privacy
policy needs a section on what happens with user data.
=> Changes to get compliance with Google Drive policies.

bin/compile_search_parser.sh
MacOS has no decent sed installed, but ex editor seem to work.
Ready to merge after review.
=> Make script Mac-compatible

src/components/SyncServiceSignIn/index.js
The Bitwarden password manager has a nice feature where you can configure it to auto-populate certain form fields if they have the right attributes set:
- https://bitwarden.com/help/article/custom-fields/
It was already successfully auto-populating the Username and Password fields on the WebDAV sign-in form, so add a name attribute to the URL sign-in field in order to allow it to populate the Url field too.
=> Allow Bitwarden to auto-populate the WebDAV URL sign-in field

src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/__snapshots__/OrgFile.integration.test.js.snap, src/components/OrgFile/components/AttributedString/index.js, src/reducers/org.unit.test.js, test_helpers/fixtures/main_test_file.org
Make a link like `[[file:foo/bar.org][bar]]` into `href="foo/bar.org"` without `target="_blank"`, so that it opens in the same organice window.  This allows more convenient navigation around a network of `.org` files, and in particular an `index.org` file which facilitates quick jumping to the most commonly used other `.org` files.
=> Make local file:... links navigate to the relevant file

src/components/Landing/index.js, src/components/Landing/stylesheet.css
As discussed on Matrix.  Not sure whether to ditch the `.view-sample-button` CSS rule; to me it looks best with the same `margin-top` as the other two buttons.
=> doc: Add a button on the landing page linking to the docs

src/components/Landing/__snapshots__/Landing.test.js.snap
The recent changes to the landing page broke the test against this snapshot.  I'm guessing that CircleCI did not spot this due to a manual merge+push which skipped the normal GitHub PR workflow.
=> Fix landing page snapshot

src/actions/org.js, src/components/OrgFile/OrgFile.unit.test.js, src/lib/export_org.js, src/lib/parse_org.js, src/lib/parse_org.unit.test.js, test_helpers/fixtures/todo_keywords_interspersed.org
~~**N.B. This PR is currently stacked on top of #309, so a) please do not merge yet, and b) you only need to review the last commit of the three.  Once #309 is merged, I can rebase this on top of the merge, and it will become a single commit.**~~
Move parsing of TODO keyword sets (i.e. `#+TODO:` and `#+TYP_TODO:` lines) and other `#+...` config lines into a separate pass which happens before the main parsing loop.  This means that these lines can appear anywhere in the file and will still take effect, just like they do in emacs.  Also add support for `#+SEQ_TODO:` which means the same thing.
Since these lines can now appear anywhere, after collecting them into `todoKeywordSets`, it no longer makes sense to use `todoKeywordSets` to regenerate them in the export.  So in order for …
=> Parse TODO keyword sets correctly from anywhere in the file (#151)

changelog.org, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/__snapshots__/OrgFile.integration.test.js.snap, src/components/OrgFile/components/AttributedString/index.js, src/components/OrgFile/index.js, src/lib/org_utils.js, src/reducers/org.unit.test.js, src/sync_backend_clients/dropbox_sync_backend_client.js, test_helpers/fixtures/main_test_file.org
The new logic for rendering `file:` links introduced by #307 had a number of issues:
- It created links for absolute paths, which does not make sense since there is no fully general mapping between the filesystem and any of the sync backends.
- It created links for relative paths pointing outside the backend (e.g. `../../../../foo.org`),
- It used `<a href="...">` rather than `<Link to=...>`, which meant the PWA treated them as external links.
So create a `<Link>` for relative `file:` paths pointing to `.org` files, don't link other `file:` paths, and render all other links with `<a ...>` as before.
Fixes #311.
=> Fix rendering of file: links  (#311)

src/lib/org_utils.js
Doing a `reverse()` just to `find()` the last header matching some predicate is needlessly expensive; so just use `findLast()` instead:
https://immutable-js.github.io/immutable-js/docs/#/List/findLast
Partially addresses #321.
=> Use findLast() instead of reverse() and find()

src/lib/org_utils.js, src/reducers/org.js
Many places in the code had adopted the following pattern:
const header = headerWithId(headers, headerId);
const headerIndex = indexOfHeaderWithId(headers, headerId);
However this is twice as slow as necessary, because `headerWithId()` calls `indexOfHeaderWithId()`, and then throws away the result after using it to return the header.
So instead build a single `indexAndHeaderWithId()` function which obtains the index, does an O(1) lookup to obtain the header, then returns an object containing both.
Partially addresses #321.
=> Double performance of obtaining header and index for given header id

src/components/OrgFile/OrgFile.unit.test.js, src/lib/parse_org.unit.test.js
There were a bunch of tests identically or near identically duplicated between `parse_org.unit.test.js` and `OrgFile.unit.test.js`, so remove them from one of the two files.  The former seems to be a more specific and low-level set of tests; based on the file name presumably it's the best place for testing `parseOrg()`, but probably less suitable for tests which also exercise `exportOrg()`.
=> Remove unit tests duplicated in parse_org.unit.test.js

.eslintrc.yml, README.org, changelog.org, sample.org, src/components/OrgFile/components/CaptureModal/index.js, src/reducers/org.js, src/reducers/org.unit.test.js
~~Currently based on #344 (eslint PR) so that I can use eslint to verify the changes are clean.~~ **Now rebased**
If no headers are in the header path list, insert at the end of the file, or the beginning if the Prepend option is set.
Lightly tested.
=> Allow capture templates to insert at beginning or end of file

README.org, WIKI.org, doc/webdav/Dockerfile, doc/webdav/webdav.conf
At this time, I cannot test any new proposed WebDAV configuration. When I wrote the original docs, I did set this up locally, so that I could test WebDAV. Since then, I have switched computers and haven't set this up, again.
The best way to move forward would likely be to create this Apache setup in a `Dockerfile`. I've been thinking of doing that for some time now. It would ease a lot of discussions on the topic of WebDAV. Right now, everyone is using some very specific setup (NextCloud, HA Proxy, Apache, etc) and it's not really possible to give support for that. Such Ops topics are way out of scope of a SPA project. If we had an official example Docker container that works for us and we use in development, we can always point to that one.
=> doc: WebDAV test setup

README.org, WIKI.org, bin/compile_doc.sh, doc/webdav/webdav.conf
Using the `R=200` trick in mod_rewrite seems problematic, because it can cause Apache to return a `200 OK` response with a very unhelpful message body including:
The server encountered an internal error or misconfiguration and
was unable to complete your request.
This SO answer suggests that the internal error is due to Apache not having an `ErrorDocument` configured for `200` responses by default:
- https://stackoverflow.com/a/48529566/179332
Apparently a `204` code (`No Content`) is a more appropriate response:
- https://stackoverflow.com/questions/27703871/return-empty-response-from-apache/
and indeed my experiments confirm that changing the `RewriteRule` to use `R=204` eliminates this error.
However, this approach doesn't guarantee that the CORS headers are included in the response. …
=> Use a more robust approach to enabling CORS pre-flight checks

.circleci/config.yml
This reduces the risk of merging broken docs.  Run this in parallel
with the normal build to save time.
If this works, it can supersede #360.
=> CI: Add parallel doc compilation to CircleCI config

bin/compile_doc_and_upload.sh
This is particularly important for CircleCI's deploy phase, otherwise it incorrectly thinks that `compile_doc_and_upload.sh` has succeeded when it hasn't.
=> Ensure non-zero exit code if compile_doc.sh fails

changelog.org, src/actions/org.js, src/components/OrgFile/components/ActionDrawer/index.js
Closes #252
- When the user put organice into the background during a sync and comes back, organice was stuck in sync mode, but doesn't actually sync anymore. This means that any new changes to the Org file will not be persisted. This is due to mobile browsers cutting off most resources to browser apps in the background, so organice cannot guarantee that a sync happens properly in the background.
- It's not trivial to find out if the job is stuck
- Time is not a good indicator as bigger files on slower connections will always take longer.
- There's no JS API to reliably find out if the browser just got back from the background or is put into the foreground. The [[https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API][=visibilitychange= API]] just triggers for both these …
=> fix: Sync stuck when working in the background

src/reducers/org.unit.test.js
redux-undo has two stages for the state history:
first the result of an undoable action (the one that was not filtered by the `filter`
config parameter to the `undoable` function) gets into the `_lastUnfiltered`
transit field, then on the next undoable action it gets stored into the `past`
stack is used to retrieve the previous versions of the state.
The test did not provide any undoable action before running INSERT_CAPTURE
so when it was run redux-undo did not push the previous state into 'past'
and could not retrieve it when and UNDO was requested.
With this PR the test first performs an undoable action to warm up the redux-undo history,
and then checks the stack property of the state history.
=> Fix the INSERT_CAPTURE 'is undoable' test

package.json, src/actions/org.js, src/lib/timestamps.js, src/reducers/org.js, src/reducers/org.unit.test.js, test_helpers/fixtures/checkboxes.org, test_helpers/fixtures/more_tags.org, test_helpers/fixtures/nested_header.org, test_helpers/fixtures/table.org, test_helpers/fixtures/various_todos.org
I would like to propose a test suite for the org format transformers implemented in `src/reducer/org.js`.
This suite covers up to 99.36% of all the statements, which boosts confidence in refactoring and implementing new features.
This changeset touches almost exclusively the test code, except for the following changes in the non-test code:
- package.json: add the coverage target (running `yarn coverage` yields detailed test coverage statistics)
- src/actions/org.js: add a comment clarifying the expected values in the `updateTimestampWithId` arguments
- src/lib/timestamps.js: add a `timestampForDate` function to enable tests involving timestamps
- src/reducers/org.js:
- fix the potential moveHeaderDown null-reference access
- Eliminate dead code, provided …
=> Increase the test coverage for src/reducer/org.js

src/reducers/org.js, src/reducers/org.unit.test.js
As discussed in: https://github.com/200ok-ch/organice/pull/431#issuecomment-680136909
A catch-all default case might potentially conceal a bug if a new checkboxState is introduced, or a checkboxState is set into an invalid state by mistake. This change forces the code to crash, i.e. fail-stop.
The production build is not affected. 
Unfortunately, I wasn't able to check if this change does not reintroduce the lint warning. When I run `yarn lint` even with a deleted the `default` case, here is the output:
```
yarn run v1.22.4
$ yarn eslint && yarn prettier-eslint --list-different
$ ./node_modules/.bin/eslint --cache .
/home/necto/proj/organice/src/reducers/org.unit.test.js
143:5  warning  Test has no assertions  jest/expect-expect
262:5  warning  Test has no assertions  jest/expect-expect …
```
=> Handle a checkbox in an invalid state: throw in dev; ignore in prod

changelog.org, src/actions/base.js, src/actions/org.js, src/components/OrgFile/components/Header/index.js, src/components/OrgFile/components/TitleLine/index.js, src/components/OrgFile/index.js, src/components/Settings/index.js, src/lib/org_utils.js, src/reducers/base.js, src/reducers/org.js, src/reducers/org.unit.test.js, src/util/settings_persister.js
Addressing the bug found in #431:
If a user folds a header, all its subheaders should collapse as well, so that when the user reopens it, they stay closed.
The previous behavior is buggy in a way that it keeps the subheaders open as they were, restoring their openness when the header is unfolded.
The previous behavior is useful at least for two users of organice (@munen and myself), so this change set also introduces a user setting.
=> Fix subheader fold propagation

changelog.org, src/components/OrgFile/components/SearchModal/index.js, src/components/OrgFile/components/TaskListModal/index.js
Closes #404 
I thought, I already had an [`autofocus` attribute](https://developer.mozilla.org/de/docs/Web/HTML/Element/Input) on the input fields once, but they have no effect. In React the attribute must be `autoFocus`: https://blog.danieljohnson.io/react-ref-autofocus/
=> Auto-focus filter input fields

changelog.org, sample.org, src/components/OrgFile/components/CaptureModal/index.js, src/components/OrgFile/components/SearchModal/index.js, src/components/OrgFile/components/TaskListModal/index.js, src/lib/browser_utils.js
Closes #454.
Unfortunately, the 'fix' is to disable auto-focus for iOS. Rationale:
On iOS, setting autoFocus in the `Modal` will move the contents of the
drawer off the screen, because the keyboard pops up late when the
height is already set to '92%' in the `Drawer`. With Redux, we could
certainly propagate a height back, but that seems hacky and there's
other complications:
- There's no API to check if the keyboard is open or not. 
- When setting the height of the container to something like 48% for iOS, this works on iPhone (tested on Xs and 6S), but when the keyboard is closed, the container is still small when the user wants to read the longer list without the keyboard in the way.
There might be a better way: If the drawer wouldn't move, iOS likely
would set the heights correctly …
=> fix: UX regression for iOS on Search and TODO List

package.json, public/index.html, src/components/CaptureTemplatesEditor/components/CaptureTemplate/index.js, src/components/HeaderBar/index.js, src/components/Landing/__snapshots__/Landing.test.js.snap, src/components/Landing/index.js, src/components/OrgFile/components/AttributedString/index.js, src/components/OrgFile/index.js, src/components/PrivacyPolicy/index.js, src/components/Settings/index.js, src/components/UI/ExternalLink/index.js
The first examples looked like this interface is good: `<ExternalLink href="url" content="text" />`
But later, I stumpled upon links with HTML tags inside, so it's probably better to allow children as described here: https://reactjs.org/docs/composition-vs-inheritance.html
Any reason to keep the `content` property and only use its value instead of childen if no children? Maybe it's a little bit shorter? But I think it's cleaner to have only one "interface".
=> Replace some <a> tags with <ExternalLink>

changelog.org, src/base.css, src/components/OrgFile/components/HeaderList/stylesheet.css
On Desktop the headerbar isn't sticky, since the scrollcontainer is the html-body. The whole #root-div itself scrolls inside of it, headerbar included. If the org-file is long enough I get an inner scrollbar for the #root-div and an outer scrollbar for the html-body.
On mobile I get an inconsistent experience. When I scroll to the top and back down, sometimes the headerbar stays, sometimes it scrolls away. Both scrollbars are present there too, but I don't know what determines which one is used.
This change fixes the issue on desktop browsers. I have not tried it on mobile yet but it works on browser-simulated mobile dimensions.
=> improve header stickiness

changelog.org, sample.org, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/components/Header/components/HeaderActionDrawer/index.js, src/reducers/org.js
Issue #246
When a header is focused, should there be an indication in the search modal that search is limited?
I think it's ok as a standard behaviour without notification but not everyone might agree.
=> only search subheaders if a header is focused

changelog.org, sample.org, src/actions/org.js, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/components/ActionDrawer/index.js, src/components/OrgFile/components/Header/components/HeaderActionDrawer/index.js, src/components/OrgFile/components/Header/index.js, src/components/OrgFile/components/HeaderList/index.js, src/reducers/org.js, src/reducers/org.unit.test.js
This is according to the naming in Emacs: https://www.gnu.org/software/emacs/manual/html_node/emacs/Narrowing.html
=> refactor: 'focusing' becomes 'narrowing'

README.org
It seems that localhost must be defined as a redirect uri. It no longer works by default.
=> documentation dropbox-app

bin/compile_and_upload.sh, bin/compile_doc.sh, bin/compile_doc_and_upload.sh, bin/compile_search_parser.sh
This fixes some shebang lines for NixOS, which does not have a `/bin/bash`. The only thing NixOS has in `/bin` is `/bin/sh`, and the only thing it has in `/usr` is `/usr/bin/env`.
=> fix: use a NixOS-compatible shebang line for bash in compile scripts

src/middleware/toggle_color_scheme.js
Closes #544.
Dark mode detection fails for devices/operating systems not supporting dark mode natively.
=> fix: Dark mode detection

changelog.org, src/migrations/index.js, src/migrations/migrate_nonsense_values_in_localstorage.js, src/util/settings_persister.js, src/util/settings_persister.test.js
Based on #553 
For me, this resulted once in showing this console:
Looking at localStorage now, all remaining entries look reasonable.
=> fix: Remove previously stored bogus values from localStorage

src/util/settings_persister.js, src/util/settings_persister.test.js
=> fix: Actually use and persist default settings

.circleci/config.yml, README.org, src/components/Settings/index.js
For regular features, fixes, documentation, nothing changes.
For longer lived features (aka epics), we now have a process and automation to work on those.
The productive reference instance of organice is deployed to <https://organice.200ok.ch/>. On merging a pull request to `master`, code and documentation are automatically deployed to production.
For more complicated features (aka epics) that require more than one pull request, there is a reference stage instance on <https://staging.organice.200ok.ch/>. When working on epics, we follow the popular [nvie git branching model](https://nvie.com/posts/a-successful-git-branching-model/) in that we successively create feature branches against `develop` until the epic is finished. On merging a pull request to `develop`, code and documentation …
=> Automatic deployments to production and stage instances

changelog.org, src/base.css
This one surely needs some discussion.
One of the main points that contributes to a bit of a clunky feel for me when using organice is accidentally selecting text - especially but not only on desktop browsers.
It might come in handy from time to time to copy things straight out of the browser without having to enter edit mode and copy things piecemeal, but - at least for me - the negative effect on regular use outweigh this rare benefit.
If there is a bunch of users that like the ability to copy text out of the main header list, we could add this behind a setting by switching a css variable. If I'm the only one that is bothered by accidentally selecting text, then I will humbly close this pr unmerged ;)
=> disable user select

src/App.js, src/actions/base.js, src/actions/org.js, src/actions/sync_backend.js, src/components/CaptureTemplatesEditor/components/CaptureTemplate/stylesheet.css, src/components/Entry/index.js, src/components/FileSettingsEditor/components/FileSetting/index.js, src/components/FileSettingsEditor/components/FileSetting/stylesheet.css, src/components/FileSettingsEditor/index.js, src/components/FileSettingsEditor/stylesheet.css, src/components/HeaderBar/index.js, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/components/ActionDrawer/index.js, src/components/OrgFile/components/AgendaModal/components/AgendaDay/index.js, src/components/OrgFile/components/SearchModal/index.js, src/components/OrgFile/components/SyncConfirmationModal/index.js, src/components/OrgFile/components/SyncConfirmationModal/stylesheet.css, src/components/OrgFile/components/TaskListModal/components/TaskListView/index.js, src/components/OrgFile/index.js, src/components/Settings/index.js, src/middleware/live_sync.js, src/reducers/base.js, src/reducers/org.js, src/util/settings_persister.js
Most of this is copied and adopted from capture templates.
Options with current defaults:
- Load on startup? --false
- Include in Agenda? --true
- Include in Search? -- false
- Include in Tasklist? -- false
Loaded files without a setting entry would be handled according to these defaults. the currently viewed file will always be included in search, agenda & tasklist.
There is also refile. Should all files always be refile targets or should it be configurable?
The 'Load on startup'-option does not do anything yet.
=> file settings & sync

src/components/OrgFile/components/AgendaModal/components/AgendaDay/stylesheet.css, src/components/OrgFile/components/SearchModal/components/HeaderListView/index.js, src/components/OrgFile/components/SearchModal/components/HeaderListView/stylesheet.css, src/components/OrgFile/components/SearchModal/index.js, src/lib/org_utils.js, src/reducers/org.js
#213
At the moment the breadcrumbs always include the filename as a first element.
=> breadcrumbs for search

.gitattributes
#513
the tests expect .org files to have lf line endings so always check out .org files with lf.
=> default autocrlf & always lf for .org files

contrib/organice-webdav-traefik/Dockerfile, contrib/organice-webdav-traefik/LICENSE, contrib/organice-webdav-traefik/README.md, contrib/organice-webdav-traefik/README.org, contrib/organice-webdav-traefik/run.sh, contrib/organice-webdav-traefik/webdav.conf
This uses the [official organice Docker
image](https://organice.200ok.ch/documentation.html#docker), but adds
instructions on how to build a Docker image using
[Traefik](https://traefik.io/) to set up a WebDAV back-end for organice.
Author:
-   Sourcehut: <https://git.sr.ht/~e-v/>
-   Email: e-v\@posteo.net
Upstream repository: <https://git.sr.ht/~e-v/docker-organice-webdav>
=> doc: Add `contrib` documentation on how to setup Traefik as WebDAV back-end

contrib/organice-webdav-traefik/README.md
DOMAIN should only contain the domain name, without a protocol prefix.
=> Fix DOMAIN variable example

changelog.org, src/components/OrgFile/OrgFile.unit.test.js, src/lib/parse_org.js, test_helpers/fixtures/all_the_features.org
organice understands `:PROPERTIES:` drawers and smartly parses the values in case one of the values is a timestamp. However, parsing _all the values_ and saving the parsed result in any case will lead to wrong results. Most values of properties are just plain text and non-interactive things in Org mode.
Hence, before this fix, we'd have problems like:
Because organice believed this to be text with `_` which yields underlined text.
=> fix: Parser does not swallow property values

src/actions/base.js, src/actions/org.js, src/actions/sync_backend.js, src/components/Entry/index.js, src/components/HeaderBar/index.js, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/components/AgendaModal/components/AgendaDay/AgendaDay.unit.test.js, src/components/OrgFile/index.js, src/lib/org_utils.js, src/middleware/live_sync.js, src/migrations/migrate_access_token_to_dropbox_access_token.js, src/migrations/migrate_store_in_dropbox_to_store_in_sync_backend.js, src/reducers/base.js, src/reducers/org.js, src/reducers/org.unit.test.js, src/util/file_persister.js, src/util/settings_persister.js
part of #570
This approach saves the text of the files to localStorage. Saving the parsed file is problematic since `generateId` starts over at zero when the application is reset.
Writing to localStorage is debounced, wich is probably not really necessary, but it seemed right to do it the same way as syncing to backend.
=> persist files to localStorage

changelog.org, src/actions/base.js, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/components/AgendaModal/index.js, src/reducers/base.js, src/util/settings_persister.js
#220
It's the staight forward solution, not the nice generic functionality @munen imagined.
=> persist agenda timeframe

changelog.org, src/actions/org.js, src/components/OrgFile/components/HeaderContent/index.js, src/components/OrgFile/components/TimestampEditorModal/components/TimestampEditor/index.js, src/components/OrgFile/components/TimestampEditorModal/index.js, src/components/OrgFile/components/TitleLine/index.js, src/components/OrgFile/index.js, src/lib/parse_org.js, src/reducers/org.js, src/reducers/org.unit.test.js, test_helpers/fixtures/various_todos.org
Repeaters on simple timestamps are broken.
When the todo state changes, the last repeat property is created, a log entry is written and the planning item in the redux state is updated. The part in the title or description that represents the timestamp is not touched though, so while the item moves in the agenda, the change is not represented in text and is not persisted.
This fix connects the timestamps in title and description with their representation in planning items by keeping the id instead of generating a new one. It fixes the issue. I'm quite sure but not 100% certain that having planning items with the same id as parts of title or description won't cause problems. It makes sense, since the items with the same id represent the same thing. If it's preferred I could instead put a …
=> fix repeater for simple timestamps

.editorconfig
This ensures that many editors can automatically configure themselves to the right indentation style to be consistent with this codebase, as per https://editorconfig.org/
----
#
=> Set up editor indentation correctly

README.org
Previously, it worked for the GH readme, but not in the official organice docs. Now it works for both.
=> doc: Fix test badge rendering in documentation

src/actions/base.js, src/components/OrgFile/components/AgendaModal/index.js, src/components/Settings/index.js, src/components/UI/TabButtons/index.js, src/reducers/base.js, src/util/settings_persister.js
WISOTT. One caveat is that I changed the default start of the week to Monday from Sunday to align with the default in Org to minimize surprise for people coming from Org (at the expense of surprising longtime Organice users).
Controls in the settings:
=> Implement an equivalent of org-agenda-start-on-weekday #266

changelog.org, sample.org, src/lib/parse_org.js, src/lib/parse_org.unit.test.js, src/lib/timestamps.js
This PR aims to make Organice recognize timestamps with "repeater deadlines" (not sure what the official name is), the `/4d` part of `<2009-10-17 Sat .+2d/4d>`, before org-parser is integrated into Organice. A nongoal is to make repeater deadlines editable in the pretty timestamp UI (which shouldn't be the end of the world for most cases because you can edit timestamps manually).
Explanation of the changes:
- The timestamp structure defined in src/lib/timestamp.js now includes repeater deadlines so that they are preserved across edits and TODO state toggles.
- In the parser, `timestampRegex` is modified to recognize repeater deadlines. This increases the number of captures in this regexp by four.
- To reflect the change in the number of capture groups, some indices are shifted by 4 or 8, …
=> Parse and preserve repeater deadlines #277

src/components/SyncServiceSignIn/index.js
The regression was introduced in https://github.com/200ok-ch/organice/pull/675 when upgrading Dropbox from 7.1.0 to 9.8.0.
Here are the docs from Dropbox with the relevant changes for upgrading: https://github.com/dropbox/dropbox-sdk-js/blob/main/UPGRADING.md#1-unblocking-browser-pkce-flow
Interestingly, I did those before pulling in https://github.com/200ok-ch/organice/pull/675. I distinctly remember. But I must have messed up in the rebasing - or the Dependabot (dependabot-preview) did.
In any case, apologies to those users who experienced issues while trying to login to Dropbox🙏
=> fix: Dropbox sign in

changelog.org, sample.org
@schoettl @branch14 @tarnung organice will not reflow if there's hard-wrapped content. This is a small workaround for the time being. It won't do anything if these files are edited with a different editor than Emacs, but at least it'll be a reminder(;
=> fix: Disable hard wrapping for sample and changelog

src/sync_backend_clients/gitlab_sync_backend_client.js
Ultra trivial PR: need two newlines between title and body for git commits. Oops... my bad.
BTW I meant to mention before, but if you get any bug reports related to the GitLab backend you're welcome to `@mention` me to fix them.
=> Fix GitLab commit message

changelog.org, src/lib/timestamps.js
Should fix #683
Since I'm still not using emacs, someone might want to check if my assumptions based on [org mode docs](https://orgmode.org/manual/Repeated-tasks.html#Repeated-tasks) are correct.
using ".+":
- when repeaterUnit is not "h", hour and minutes are never touched.
- when repeaterUnit is "h", hour and minutes are set to n hour(s) from now (as it was already implemented before this fix)
=> fix repeater adjusting time of date

sample.org, src/colors.css, src/components/OrgFile/components/ActionDrawer/index.js, src/components/OrgFile/components/ActionDrawer/stylesheet.css, src/lib/clocking.js, src/lib/parse_org.js, src/reducers/org.js
A quick and dirty implementation for parts of the feature set described in #737
=> clock:now searches for active clocks
I thought that other things than clocks can create "logBookEntries". But maybe i misremember. I could not find any in my demo files.
This pull request does not address the issue #745. Since it does not add to the problem we can go along and refactor later once @schoettl and I what if anything should be done.
=> feat: suggestion for clock:now

changelog.org, sample.org, src/App.js, src/actions/org.js, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/__snapshots__/OrgFile.integration.test.js.snap, src/components/OrgFile/components/SearchModal/index.js, src/components/OrgFile/components/SearchModal/stylesheet.css, src/components/OrgFile/components/TaskListModal/index.js, src/components/OrgFile/components/TaskListModal/stylesheet.css, src/lib/headline_filter.js, src/reducers/org.js, src/util/settings_persister.js
Simple search string bookmarking.
The initial idea of saving the last 10 used search strings is not practical because we search on every keystroke. The most obvious way to identify useful complete search strings is to let the user decide when to bookmark.
Bookmarked search strings populate the suggestions if no search string is entered into the input field.
Bookmarks are saved by context, so there are separate bookmarks for search, task-list and refile.
There are at most 10 bookmarks for a context. New saved bookmarks are inserted at the top of the list. If the list gets too long, the last search strings are dropped. Duplicate bookmarks are dropped too. The list of bookmarks is ordered by last used.
Bookmarks are at the moment unaware of file context. You always have the same bookmarks. …
=> bookmark searches

changelog.org, src/components/OrgFile/components/TitleEditorModal/index.js, src/components/OrgFile/index.js
The title editor modal in semantic edit mode persists its content on different schedules.
- the todo keyword is saved on click
- the title text is saved on close
This leads to the following behaviour:
If you modify the text of a title and then click a todo, the todo keyword gets saved which triggers a rerender before the text got saved. Therefore the text is reset to the state it was in when the title editor was opened.
As a solution I save the title text before updating the todo-keyword.
=> fix title editor text loss

public/index.html
As discussed in #779 
Since the manifest generation happens inline, `absoluteUrl()` is defined in the global namespace, hopefully does not lead to problems.
I have based the PR on `master`, if it shall be based on another branch, I'm happy to change it!
=> Fixed manifest for PWAs, fixes #779

.env.sample, src/components/SyncServiceSignIn/index.js
Added the feature to specify the REACT_APP_WEBDAV_URL in the .env file and have the sign-in page pre-fill in that field based on your default preference.  This variable is optional in the .env file
=> Specify default webDAV URL in .env file

Dockerfile, README.org, bin/entrypoint.sh, bin/transient_env_vars.sh, changelog.org, docker-compose.yaml
This uses an 2 step approach (**bait & switch**) to inject the values of environment variables post compilation.
Step 1: Scan `.env.sample` and build a dummy `.env` file (**bait**) that injects dummy strings that can be replaced post compilation.
Step 2: After compilation replace (**switch**) the dummy strings with the value of corresponding env vars. (This is cheap and runs on every start of the docker container.)
=> feat: transient env vars

doc/webdav/Dockerfile
Otherwise there's a routing conflict between the actual sample.org file and the demo file.
That means, that anyone who has a `sample.org` file might still run
into the problem. The better fix would be, of course, to treat the
sample.org file differently. However, that would be a bigger refactor which could be done by the person requiring to have a file in her root directory to be called `sample.org`.
=> fix: Rename sample demo file in bundled WebDAV image

src/actions/sync_backend.js
Use Node.js `path.parse(pathString)` ponyfill instead of custom code.
=> refactor: `dirName` function

src/components/CaptureTemplatesEditor/components/CaptureTemplate/index.js, src/lib/capture_template_substitution.js
Added %r and %R to the capture template input form and substitution code, so you can specify dates with modifiers in capture templates, such as <%r ++60d>
Currently if you use %t you would get (as an example) <<2022-06-13> ++60d> (which is invalid) - and the same is true for %u but with brackets
=> Added capture template variables to enable advanced dates

src/App.js, src/components/Entry/index.js, src/components/Settings/index.js, src/components/SwitchComponent/index.js, src/components/Turnout/index.js, src/sync_backend_clients/gitlab_sync_backend_client.js, src/util/misc.js
We are running different kinds of pages in our SPA (see [ADR-002](https://organice.200ok.ch/documentation.html#adr-002)).
Currently, the `<Entry />` component has conflated logic for rendering the LP and the actual application. This makes the code more complex and can yield unexpected side effects.
Todos:
=> fix: Conflated Routing

src/actions/sync_backend.js
NOTE: This is a bad (non-)solution to https://github.com/200ok-ch/organice/issues/848 However, it is a safeguard in case authentication for sync back-ends expires. It's better than to show a 401 and require the user to sign off manually.
Background why this can happen right now: Dropbox is in the process of switching to only issuing short-lived access tokens. They started migrating apps on September 30th 2021. They are releasing it gradually, so some apps may not have been affected until now.
https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/dropbox-exceptions-AuthError-expired-access-token/td-p/580407
Followup: We should be looking into Dropbox refresh tokens. More info in #848.
Leaving this PR for reference until then.
=> fix: Automatically sign out when Dropbox has expired access token

changelog.org, src/actions/org.js, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/index.js, src/reducers/org.js, src/reducers/org.unit.test.js, test_helpers/fixtures/content_but_no_headline.org
Original issue: https://github.com/200ok-ch/organice/issues/583
This takes care of a big UX problem for users who solely rely on organice. So far, we've shown a parser error if the file is empty *or* if the file did not contain a headline.
Now, if the user opens a file that is completely empty, she has this flow:
On Click:
If the file already contains content (but not a headline), the user is shown this optimized screen:
Of course, this also works when the user deletes the final headline.
=> feat: Handle empty files

changelog.org, src/components/HeaderBar/stylesheet.css
Closes: https://github.com/200ok-ch/organice/issues/865
=> fix: Make header sticky

changelog.org, src/components/OrgFile/index.js
Reported in https://github.com/200ok-ch/organice/issues/864
The regression was visible, for example, when going first to settings and then to the changelog. The changelog would then show in a 'scrolled down' position.
=> fix: Start from the top

changelog.org, sample.org, src/lib/headline_filter.js, src/lib/headline_filter_parser.grammar.pegjs
As discussed in https://github.com/200ok-ch/organice/issues/511, this PR adds the ability to search any text in the description of a node.
To search the description use the syntax `desc:"search term"`.
New tests will need to be added.
=> Add filtering by description

changelog.org, src/components/OrgFile/__snapshots__/OrgFile.integration.test.js.snap, src/components/OrgFile/components/SearchModal/index.js, src/components/OrgFile/components/TaskListModal/index.js
This disables auto-capitalization for the search fields on Android Chrome as described here: https://github.com/200ok-ch/organice/issues/913
This is tested only on Chrome for Android only. I also checked Firefox for Android, this works fine (no auto-capitalization) with or without this change.
I'm unable to test with iOS, so that should be checked carefully for regressions.
=> Disable auto-capitalization for search

changelog.org, src/lib/export_org.js
This is related to the issue https://github.com/200ok-ch/organice/issues/376. When we have a check box and whenever we check or uncheck it if we have an inline markup in the description it is getting disappeared. 
There is a switch case for each type to convert to raw text and here the "inline-markup" case is missing. I have written a separate function to handle this text and added the case there.
=> 376 - fixed text discards while check/uncheck box when text has inline-markup

changelog.org, src/components/OrgFile/components/Header/index.js
Contrary to most other examples of swiping interactions, swiping a headline in Organice only works if you keep your finger/thumb/mouse inside the bounds of the item being dragged. This makes it rather difficult to swipe reliably, especially on larger devices (and/or smaller hands) since the hand naturally wants to move in an arc, while the headline bounds are linear.
This change is intended to align the swipe interaction with the behavior shared by the native interactions of both Android and IOS: that after initiating a swipe, no amount of vertical movement should cancel it.
Regarding the implementation: It works reliably in my tests, however I'm not previously familiar with React or web development in general, so please feel free to suggest better alternatives.
**Before**:
**After**:
=> Don't cancel swipe due to vertical movements

contrib/organice-caddy-webdav/Dockerfile, contrib/organice-caddy-webdav/README.org, contrib/organice-caddy-webdav/docker-compose.yml, contrib/organice-webdav-traefik/README.org, contrib/organice-webdav-traefik/docker-compose.yml
This adds a guide for setting up Organice with Caddy and its Webdav plugin.
=> Add Contrib/organice-caddy-webdav

changelog.org, src/components/CaptureTemplatesEditor/components/CaptureTemplate/index.js
Fix this use case: Using a capture template that is available from all Org files, but should always capture to just one file (not necessarily the currently open one).
=> fix: Capture template available everywhere, but capturing to one

README.org
The indentation level here was wrong, the line breaks didn't make sense to me and I think it's easier to grasp now.
=> Fix whitespaces in JS string in README

src/components/OrgFile/components/AttributedString/components/ListPart/index.js, src/lib/org_utils.js
Fix #988 where the application would crash if a list was deleted immediately after exiting edit mode for the list title (or content).
=> fix: Prevent app crash when deleting a list item immediately after exiting edit mode

README.org, sample.org
New users can struggle to find the right kind of help. The docs did not reference the interactive tutorial and the interactive tutorial did not reference the docs. Now, they do.
=> doc: Clarify where to find docs (interactive tutorial vs. manual)

public/index.html, public/manifest.json
Closes #1006 
Originally, I think we created it dynamically, because we thought the `start_url` has to be dynamic for the self hosting. However, according to current [MDN](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Manifest/Reference/start_url#start_url) this is not the case (anymore). So I think, we can go the easy route and just use a static file for every host.
For reference, here's the original implementation: https://github.com/200ok-ch/organice/pull/781
I tested this on Staging and it also looks OK to me in the dev tools:
@tbruckmaier As the original author, is it OK for you if we change the implementation as proposed in this PR?
=> fix(1006): Creating a static /manifest.json

changelog.org, sample.org, src/actions/org.js, src/components/OrgFile/components/Header/components/HeaderActionDrawer/index.js, src/components/OrgFile/components/Header/components/HeaderActionDrawer/stylesheet.css, src/components/OrgFile/components/Header/index.js, src/reducers/org.js
Closes #894 
Implements a long-press gesture on the plus icon within the
HeaderActionDrawer to duplicate the current header and its entire
subtree. This provides a quick alternative to manually recreating
similar header structures.
There's visual feedback for long-press interactions, too.
@schoettl It's taken a *loong* time, but I finally got around to your feature request. What do you say, can we use it like this?
NB: I would have liked to go with vibration feedback on mobile, but it never worked on my phone, so I went with a bit of clumsy visual feedback(;
=> feat: Add long-press to duplicate header and enhance visual feedback

changelog.org, src/reducers/org.js, src/reducers/org.unit.test.js, test_helpers/fixtures/various_todos.org
Fixes: #1011 and #750 
I found this error when I added a headline to the end of `various_todos` fixtures, right after the "Repeating task" header. I was adding new Todos as I am going to rewrite #984. Adding a new header caused the 'should advance repeating task' test to fail. It failed at the line where it asserted the `logNotes` of the entry with a repeater had changed. I was able to trace this error to addNoteGeneric where I noticed `headerId` was undefined as `state.get('selectedHeaderId')` returned undefined. However, this would never cause `addNoteGeneric` to fail since `headerId` is passed to `indexOfHeaderWithId`, which relies on `findIndex`. `findIndex` returns -1 whenever it can find an element that satisfies your testing function. That is the reason …
=> fix: repeater state changes will now be filed to the correct header

src/components/OrgFile/OrgFile.integration.test.js
The `Clicking the Timestamp in a TODO within the agenda toggles from the date to the time` test failed when I ran yarn test this morning. However, the feature itself still worked when I tested it. I was able to trace the test error to `dateForTimestamp`. `dateForTimestamp` sets the start hour of a timestamp to 12:00 if it receives a timestamp without a start time. The expected date in the test did not take this account. Now that I have taken that into account, the test no longer fails.
=> fix: Fixed timestamp error in OrgFile.integration.test.js

changelog.org, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/components/Header/components/HeaderActionDrawer/index.js, src/components/OrgFile/components/Header/index.js, src/lib/export_org.js, src/lib/share_utils.js
Closing: https://github.com/200ok-ch/organice/issues/935
Closing: https://github.com/200ok-ch/organice/issues/142
Closing: https://github.com/200ok-ch/organice/issues/142
Users can now share their headlines (including sub-headlines) to any app - with a fallback to mail.
=> feat: Implement 'deep export' and 'share' with 'mailto' fallback
