changelog.org, src/components/OrgFile/OrgFile.test.js, src/components/OrgFile/__snapshots__/OrgFile.test.js.snap, src/lib/export_org.js, src/lib/parse_org.js, test_helpers/fixtures/all_the_features.org, test_helpers/fixtures/newlines.org, test_helpers/fixtures/schedule.org
=> Preserve newlines between headers and items

package.json, src/components/OrgFile/components/CaptureModal/index.js, src/components/UI/Drawer/stylesheet.css, yarn.lock
=> fix: iOS 13 regression: On capture, focus and show input field

src/components/OrgFile/components/CaptureModal/index.js, src/components/UI/Drawer/stylesheet.css
=> fix: Set max-height for Agenda and make it scrollable

src/base.css, src/components/OrgFile/components/ActionDrawer/stylesheet.css, src/components/OrgFile/components/AgendaModal/stylesheet.css, src/components/OrgFile/components/AttributedString/components/TimestampPart/stylesheet.css, src/components/OrgFile/components/Header/components/HeaderActionDrawer/stylesheet.css, src/components/OrgFile/components/HeaderContent/components/PlanningItems/stylesheet.css, src/components/OrgFile/components/TagsEditorModal/stylesheet.css, src/components/OrgFile/components/TimestampEditorModal/components/TimestampEditor/stylesheet.css, src/components/UI/TabButtons/stylesheet.css
As a user, when I hover a clickable element, I want my cursor to change, so that I can see that it is clickable.
=> style: change button cursors

README.org, package.json, src/App.js, src/actions/base.js, src/actions/sync_backend.js, src/components/FileBrowser/index.js, src/components/SyncServiceSignIn/index.js, src/components/SyncServiceSignIn/stylesheet.css, src/middleware/sync_on_becoming_visible.js, src/sync_backend_clients/webdav_sync_backend_client.js, src/util/settings_persister.js, yarn.lock
This builds on the great work of @TristanCacqueray on this PR: https://github.com/200ok-ch/organice/pull/82
During my tests, I'll add some stuff in this PR.
=> Feat: Integrate webdav as a sync back-end

package.json, src/App.js, src/actions/base.js, src/actions/sync_backend.js, src/components/FileBrowser/index.js, src/components/SyncServiceSignIn/index.js, src/sync_backend_clients/webdav_sync_backend_client.js, src/util/settings_persister.js, yarn.lock
This change adds a new sync backend for the WebDAV protocol.
* TODO polish the signin form.
* TODO implement directory listing filter and getMore cursor.
* TODO better handle errors.
closes: #77
=> webdav: add initial sync backend

src/components/Settings/index.js
This commit fixes a one-letter typo in the Settings.
=> Fix small typo

changelog.org, sample.org, src/actions/org.js, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/components/AgendaModal/index.js, src/components/OrgFile/components/TimestampEditorModal/components/TimestampEditor/index.js, src/components/OrgFile/components/TimestampEditorModal/index.js, src/components/OrgFile/index.js, src/reducers/org.js
=> Remove planning items

src/base.css, src/components/Entry/stylesheet.css, src/components/Landing/__snapshots__/Landing.test.js.snap, src/components/Landing/index.js, src/components/Landing/stylesheet.css
=> Bugfix: Layout on LP

src/components/OrgFile/components/TagsEditorModal/index.js
issue #148 
I think this is ready to merge.
It was only a small change since the global tag list was already there.
=> Add suggestion list for tags

src/components/OrgFile/components/PropertyListEditorModal/index.js, src/components/OrgFile/index.js, src/lib/org_utils.js, src/lib/org_utils.unit.test.js, test_helpers/fixtures/properties_extended.org
=> Suggestion list for inputs in property editor

src/components/OrgFile/OrgFile.unit.test.js
Bug was discussed [here](https://github.com/200ok-ch/organice/pull/147#issuecomment-568739231)
and via Mail with @munen
=> [WIP] Failing unit tests for inline-markup

src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/components/Header/components/HeaderActionDrawer/index.js, src/components/OrgFile/components/Header/index.js
#142 
Currently only simple e-mail sharing (not yet tested on smart phones).
=> "Share" button for headlines

README.org
It's a quick draft, information taken from https://github.com/200ok-ch/organice/pull/145#issuecomment-568931656
=> Add "Testing" section to dev doc in README

src/components/OrgFile/OrgFile.unit.test.js, src/components/OrgFile/components/AttributedString/index.js, src/lib/parse_org.js
=> Refactor org parser

src/reducers/org.js
=> feat: Don't update search results when using an invalid search filter

changelog.org, src/base.css, src/components/OrgFile/components/AgendaModal/index.js, src/components/OrgFile/components/TaskListModal/components/TaskListView/index.js, src/components/OrgFile/components/TaskListModal/index.js, src/components/OrgFile/components/TaskListModal/stylesheet.css, src/components/UI/Checkbox/stylesheet.css, src/components/UI/Drawer/stylesheet.css, src/lib/browser_utils.js, src/lib/org_utils.js, src/reducers/org.js
Relevant issue: https://github.com/200ok-ch/organice/issues/182
=> Refactor Search / Task List

sample.org, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/__snapshots__/OrgFile.integration.test.js.snap, src/components/OrgFile/components/TaskListModal/components/TaskListView/index.js, src/lib/org_utils.js
This may close #205 
Tasks in done state are sorted last now.
=> Fix sort order in task list

src/components/OrgFile/components/TitleLine/index.js, src/lib/export_org.js
The integration tests fail, I cannot yet explain why.
=> Reuse function from export_org.js

changelog.org, src/reducers/index.js
=> fix: After undo/redo, synchronize Org file

changelog.org, src/actions/org.js
Closes https://github.com/200ok-ch/organice/issues/76
=> Debounce and safeguard synchronization to back-end

changelog.org, src/components/Entry/index.js, src/components/Settings/index.js, src/components/Settings/stylesheet.css
This is done with a similar UX than other productivity apps (like
Slack) do it. The user will see a 'gift' icon whenever there's a
change to the last changelog header which she has not seen, yet.
=> Notify on changes for changelog

src/components/OrgFile/components/AgendaModal/components/AgendaDay/index.js, src/components/OrgFile/components/SyncConfirmationModal/index.js, src/components/OrgFile/components/TaskListModal/components/TaskListView/index.js, src/lib/org_utils.js, src/lib/timestamps.js
=> Fix relative time distance for future dates

changelog.org, src/actions/org.js, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/components/Header/components/HeaderActionDrawer/index.js, src/components/OrgFile/components/SearchModal/components/HeaderListView/index.js, src/components/OrgFile/components/SearchModal/index.js, src/components/OrgFile/index.js, src/reducers/org.js
=> When refiling a header, don't show subheaders in the refile drawer

changelog.org, src/reducers/base.js
Closes: https://github.com/200ok-ch/organice/issues/199
=> Fix 'unpushed changes' dialog for modal views

src/lib/export_org.js
This closes #286 
New tags were appended without a space before. Always inserting a space would change the original org file (parse-export-diff).
Solution: Only if title does not end with space, insert correct number of spaces (at least one)
=> Bugfix for #286: append new tags correctly to title

src/actions/org.js, src/components/OrgFile/OrgFile.unit.test.js, src/components/OrgFile/components/HeaderContent/index.js, src/lib/export_org.js, src/lib/parse_org.unit.test.js
=> Fix problem with indent

.gitignore, CONTRIBUTING.org, README.org, WIKI.org, bin/compile_doc.sh, bin/compile_doc_and_upload.sh
- Add a page title.
- Make it easier for contributors to build the docs themselves without trying to upload anywhere.
- Fix a typo.
=> Minor documentation improvements

WIKI.org, bin/compile_doc.sh
- Fix formatting of references to doc files
- Sanity check for building docs from the right directory
=> Couple more minor doc tweaks

CONTRIBUTING.org, README.org, WIKI.org, bin/compile_doc.sh
A ragbag of doc improvements; should be self-explanatory from each commit message.
=> More doc improvements

README.org
It wasn't obvious to me, even though I've encountered that acronym before (and then forgot it).  So add "Single Page Application" just before the first mention.
This change only modifies the first half of the first sentence.  The rest is just refilling the paragraph.
=> Explain what an SPA is

src/components/Landing/stylesheet.css
Also: Don't mix 'flex' and 'position' based layouts.
Closes: #357
=> fix: Render privacy policy unobtrusively

.circleci/config.yml, CONTRIBUTING.org, package.json, src/components/OrgFile/components/AttributedString/index.js, src/components/OrgFile/components/TimestampEditorModal/components/TimestampEditor/index.js, src/lib/export_org.js, src/lib/parse_org.js, src/reducers/org.unit.test.js, src/sync_backend_clients/google_drive_sync_backend_client.js, src/sync_backend_clients/webdav_sync_backend_client.js
Fix prettier regressions, and run prettier and prettier-eslint checks in CircleCI.  Also add a `yarn lint` shortcut for easy local testing.
=> Get back on track with prettier

CONTRIBUTING.org, README.org, WIKI.org
This continues on from the work in #343, for more fully resolving #342.
=> doc: Add a bunch of CUSTOM_ID properties for permalinks

README.org, contrib/organice-k8s/LICENSE, contrib/organice-k8s/README.org, contrib/organice-k8s/deployment.yml, contrib/organice-k8s/ingress.yml, contrib/organice-k8s/load-balancer.yml, contrib/organice-k8s/service.yml
This builds on a discussion from #organice: https://matrix.to/#/!DfVpGxoYxpbfAhuimY:matrix.org/$PN-F8fb_74jS9M39KQbqDKoTuX9KbGkPRz7CNFkLQWE?via=matrix.org&via=ungleich.ch&via=tapenet.org
The PR adds some boilerplate and is subject to review by @johnhamelink who is the author of the organice-k8s contribution.
=> doc: organice-k8s contrib

README.org
i think it's meant to be this way round?
=> transpose quality and quantity

public/index.html, src/components/CaptureTemplatesEditor/components/CaptureTemplate/index.js, src/components/PrivacyPolicy/index.js, src/components/Settings/index.js
Closes #435 
Wouldn't it be a good idea to write a component for this? `<ExternalLink url=url>` or so?
=> Fix external links

src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/components/AgendaModal/components/AgendaDay/index.js
=> Bugfix after refactoring

changelog.org, src/components/OrgFile/OrgFile.integration.test.js, src/lib/parse_org.js, test_helpers/fixtures/main_test_file.org
Next to 'canonical' phone numbers like +498025123456789, also recognize:
US phone numbers:
- 123-456-7890
- (123) 456-7890
- 123 456 7890
- 123.456.7890
- +91 (123) 456-7890
Swiss phone numbers:
- 0783268674
- 041783268675
- 0041783268674
- +41783268676
- +41783268677
=> Recognize US and Swiss phone numbers

changelog.org, sample.org, src/components/OrgFile/components/TimestampEditorModal/components/TimestampEditor/index.js, src/components/UI/TabButtons/index.js
Added documentation to `sample.org` and to mouseovers for the relevant buttons.
=> doc: Repeaters and delays

package.json, src/components/SyncServiceSignIn/index.js, src/sync_backend_clients/dropbox_sync_backend_client.js, yarn.lock
Upgrading from 5.x.x to 7.x.x by following the upgrade documentation[1] and by local testing in FF and Chromium.
1. https://github.com/dropbox/dropbox-sdk-js/blob/master/UPGRADING.md
=> chore: Upgrade Dropbox SDK (2 major versions)

src/components/SyncServiceSignIn/index.js
Document on the sign in page what that means for the users and what her options are.
On sign in, there's the option to click on 'important news' for Google Drive. Then, this is shown:
=> doc: Google Drive is not in production mode for organice.200ok.ch

src/colors.css, src/components/Entry/index.js, src/lib/color.js
In preparation for supporting additional color schemes the color functions should set all colors, not just the ones that currently change between light and dark mode.
In addition I added a rough documentation to base.css.
=> set all colors when switching color scheme

src/components/Entry/index.js, src/lib/color.js
we should not spread the theme loading logic into components unnecessarily.
setting theme color for android is not yet tested, since i did not get port forwarding to work yet.
=> simplify theme loading

changelog.org, src/reducers/org.js
=> write inactive datetimestamp in log

changelog.org, src/components/OrgFile/OrgFile.integration.test.js, src/components/OrgFile/components/AgendaModal/index.js, src/components/Settings/index.js, src/components/UI/TabButtons/index.js, src/util/settings_persister.js
- Bugfix: TabButton keys were not unique (twice an `S`), that makes React throw many errors
- Ideomatic organice default value
- Tooltips for Settings
=> Refactor: #266 Org agenda start on weekday

CONTRIBUTING.org, README.org
Analogous to https://github.com/200ok-ch/org-parser/pull/48
@schoettl @branch14 @tarnung @AlexMihov @MTrost FYI
=> doc: Move to Libera.Chat from Freenode

Makefile, README.org, WIKI.org
Also:
- Add Makefile
- Add FAQ top level doc headline
- Explain how to `make docs` locally
NB: When checking out this PR, select 'hide whitespace changes'.
=> doc: Can we add feature X from plugin Y?

src/sync_backend_clients/gitlab_sync_backend_client.js
Fix for #739. This turned out to be tricky to debug but the solution is trivial, fortunately. Here's what was happening, brace yourself:
1. Signed-in user with an expired OAuth token visits https://organice.200ok.ch/files . Tangential-but-irrelevant trivia: GitLab tokens expire after 2 hours and are not refreshed until expiration, so expiration could happen even while actively using the app.
2. On startup, Organice checks if the sync client is still signed in. **Important detail**: because this occurs in a promise that isn't waited on before doing anything else, additional API calls (e.g. to fetch the config file and fetch org file contents) also happen concurrently before this finishes. https://github.com/200ok-ch/organice/blob/891716bcf9c199356a024dfde35e8a9796bdbe42/src/App.js#L168-L174 …
=> Fix GitLab OAuth token refresh

changelog.org, src/components/Settings/index.js, src/lib/color.js, src/util/settings_persister.js, src/util/settings_persister.test.js
=> add setting to respect os light/dark preferences

README.org, changelog.org, src/lib/parse_org.js
=> Fix parsing of #+todo: keyword definitions

contrib/organice-nextcloud-nginx/README.org
As [requested](https://github.com/200ok-ch/organice/issues/117#issuecomment-841815965) I've added documentation for setting up Nextcloud to add the organice application as an allowed origin.
=> Document how to allow organice access to Nextcloud

src/components/SyncServiceSignIn/index.js
Even if this is not a website but an app, I like it if labels are assigned to their inputs. Click/touch on the label will focus the assigned input.
What do you think?
And do we have special rules for choosing ID names?
=> Assign labels to their inputs

README.org, docker-compose.yaml
Closes #764 
Proof of functionality:
=> fix: Issue #784, again

changelog.org, src/actions/org.js, src/actions/sync_backend.js, src/components/FileBrowser/components/ActionDrawer/index.js, src/components/FileBrowser/index.js, src/reducers/org.js, src/reducers/sync_backend.js, src/sync_backend_clients/webdav_sync_backend_client.js
Closes https://github.com/200ok-ch/organice/issues/87
=> feat: Create new file from file browser

Makefile, src/components/SyncServiceSignIn/index.js
- shows a build number (aka revision) on the sign in screen
- make `Makefile` self-documenting (view with `make help`)
- refactor some compile and deploy scripts into `Makefile` (WIP)
=> Feat: show a build number

.circleci/config.yml, .eslintignore, .gitignore, .prettierignore, Makefile, Procfile, android/app/src/main/assets/capacitor.config.json, capacitor.config.ts, package.json
Upon merge to develop, staging should show a proper revision on the sign in view.
Also the preferred android target can now be configured in a git-ignored `local.mk`.
=> Feat: deploy via make with revision

contrib/organice-webdav-post/Readme.md, contrib/organice-webdav-post/home.php, contrib/organice-webdav-post/inbox.php, contrib/organice-webdav-post/organice_inbox.sh
Here are the script files I use for posting tasks directly to Org files via email and web browsers.  The script does some limited data validation and removes dangerous characters.  The content is also formatted and indented properly for the submitted content.
The logic is pretty simple and could possibly be written in other languages.  I am currently using 2 PHP files and 1 shell script.
=> Contrib webdav post

changelog.org, src/base.css, src/components/OrgFile/components/DrawerActionBar/components/DrawerActionButtons/index.js, src/components/OrgFile/components/DrawerActionBar/index.js, src/components/OrgFile/components/TitleEditorModal/index.js, src/components/OrgFile/components/TitleEditorModal/stylesheet.css
Closes: https://github.com/200ok-ch/organice/issues/774
Before:
After:
=> Some UX changes in task modal

changelog.org, src/actions/org.js
=> fix: Undo/Redo persists to storage, again

package.json, src/App.js, src/actions/sync_backend.js, src/components/SyncServiceSignIn/index.js, src/sync_backend_clients/dropbox_sync_backend_client.js, yarn.lock
Closes: https://github.com/200ok-ch/organice/issues/848
=> Upgrade Dropbox, switch to OAuth 2 and PKCE

changelog.org, src/App.js, src/components/Entry/index.js, src/components/HeaderBar/index.js, src/components/Settings/index.js
=> fix: Proper route for changelog

README.org
Closes: https://github.com/200ok-ch/organice/issues/880
=> fix: Rendering of HTML in documentation

public/index.html
Thanks for this project!!
Joseph Turner
=> fix: Use correct HTML anchor tag inside public.html <noscript>

changelog.org, src/components/OrgFile/OrgFile.unit.test.js, src/lib/parse_org.js
Fixes issue #198, passes new tests in PR #157.
=> Parse inline markup non-greedily

README.org, changelog.org, src/components/Entry/index.js, src/components/FileSettingsEditor/components/FileSetting/index.js
=> feat: Configuration option for default file on startup

changelog.org, src/components/OrgFile/components/DescriptionEditorModal/index.js
=> fix: Don’t replace all leading * in the description

README.org
Looks like Firefox has changed how to do this. I'm on the most recent version of Firefox (on a Pixel, fwiw), but can't vouch that this is the process for most Firefox versions (or android devices) in use, so I'm happy to "append" this rather than editing the old version, if you'd prefer.
=> Update Android/Firefox instructions in README

changelog.org, src/components/OrgFile/components/AttributedString/components/ListPart/index.js
As discussed in https://github.com/200ok-ch/organice/discussions/950
@neildavidforrest and @kjmatsuda: Can you please test this PR and see if it is to both of your liking?
=> feat(ux): Ticking a checkbox as part of a list item

src/components/Landing/__snapshots__/Landing.test.js.snap, src/components/Landing/index.js
Noticed this- I'm sure it's how I originally typed it, but would like to fix the grammar since my name is on it 😁
=> fix: grammar on testimonial

README.org, changelog.org, flake.lock, flake.nix
It's still not trivial to get it run on NixOS...
=> Add basic flake.nix to get a dev shell on NixOS

changelog.org, src/components/OrgFile/components/Header/index.js
Closes https://github.com/200ok-ch/organice/issues/995
=> fix(995): Swiping vertically on iOS also allows horizontal swiping

changelog.org, sample.org, src/components/OrgFile/components/Header/index.js, src/components/OrgFile/components/Header/stylesheet.css, src/components/OrgFile/components/TitleLine/index.js
Original PR by @dmorlitz: https://github.com/200ok-ch/organice/pull/970
=> feat: Add visual cue for overdue headers when displaying headers
